server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.10.100:3307/sby-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
      username: root
      password: 12345678
  # --- 开发环境 Redis 地址 ---
  data:
    redis:
      host: 192.168.10.100
      port: 6379
      password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发环境控制台打印执行SQL
    map-underscore-to-camel-case: true                # 开启下划线转驼峰