server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/sby_db_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
      username: root
      password: dev_password

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发环境控制台打印执行SQL
    map-underscore-to-camel-case: true                # 开启下划线转驼峰